openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description: The library service

tags:
  - name: "Payment"

paths:

  /payment/updateOrder:
    post:
      summary: Endpoint for the Update Order use case
      tags:
        - "Payment"
      description: Refer to summary
      operationId: updateOrder
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/payment_UpdateOrderRequest"
      responses:
        "200":
          description: Returns updated order upon success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/payment_UpdateOrderResponse"

  /payment/submitOrder:
    post:
      summary: Endpoint for the Submit Order use case
      tags:
        - "Payment"
      description: Refer to summary
      operationId: submitOrder
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/payment_SubmitOrderRequest"
      responses:
        "200":
          description: Returns submitted order upon success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/payment_SubmitOrderResponse"

  /payment/getStatus:
    post:
      summary: Endpoint for Get Status use case
      tags:
        - "Payment"
      description: Refer to summary
      operationId: getStatus
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/payment_GetStatusRequest"
      responses:
        "200":
          description: Returns status upon success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/payment_GetStatusResponse"

  /payment/getItems:
    post:
      summary: Endpoint for Get Items use case
      tags:
        - "Payment"
      description: Refer to summary
      operationId: getItemsPayments
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/payment_GetItemsRequest"
      responses:
        "200":
          description: Returns status upon success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/payment_GetItemsResponse"

  /payment/getCustomersActiveOrders:
    post:
      summary: Endpoint for the customers getting their active order
      tags:
        - "payment"
      description: Refer to summary
      operationId: getCustomerActiveOrders
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/payment_GetCustomersActiveOrdersRequest"
      responses:
        "200":
          description: Returns the orderID of the active order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/payment_GetCustomersActiveOrdersResponse"

  /payment/getOrder:
    post:
      summary: Endpoint for getting of an order by UUID
      tags:
        - "payment"
      description: Refer to summary
      operationId: getOrder
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/payment_GetOrderRequest"
      responses:
        "200":
          description: Returns the order object of the order
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/payment_GetOrderResponse"

  /payment/getOrders:
    post:
      summary: Endpoint for getting all the active orders
      tags:
        - "payment"
      description: Refer to summary
      operationId: getOrder
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/payment_GetOrdersRequest"
      responses:
        "200":
          description: Returns the active orders
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/payment_GetOrdersResponse"
components:

  schemas:

    ItemObject:
      description: "Generic schema for an item"
      type: object
      properties:
        productId:
          type: string
        name:
          type: string
        barcode:
          type: string
        storeId:
          type: string
        price:
          type: number
        quantity:
          type: integer
        description:
          type: string
        imageUrl:
          type: string
        brand:
          type: string
        size:
          type: string
        itemType:
          type: string

    OrderObject:
      description: "Generic schema for an Order"
      type: object
      properties:
        orderId:
          type: string
        userId:
          type: string
        storeId:
          type: string
        shopperId:
          type: string
        createDate:
          type: string
        processDate:
          type: string
        totalPrice:
          type: number
        status:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/ItemObject"
        discount:
          type: number
        deliveryAddress:
          $ref: "#/components/schemas/GeoPointObject"
        storeAddress:
          $ref: "#/components/schemas/GeoPointObject"
        requiresPharmacy:
          type: boolean

    payment_UpdateOrderRequest:
      description: This object is expected as input
      type: object
      properties:
        orderId:
          type: string
          description: the id of the order to be generated
        items:
          type: array
          items:
            $ref: "#/components/schemas/ItemObject"
        discount:
          type: number
        orderType:
          type: string
        deliveryAddress:
          $ref: "#/components/schemas/GeoPointObject"

    payment_UpdateOrderResponse:
      description: This object is expected as output
      type: object
      properties:
        message:
          type: string
          description: Will contain a descriptive error message if response code is not 200, else will be empty
        success:
          type: boolean
        timestamp:
          type: string
        order:
          type: object

    payment_SubmitOrderRequest:
      description: This object is expected as input
      type: object
      properties:
        jwtToken:
          type: string
          description: generated token used to identify the caller of the endpoint
        listOfItems:
          type: array
          items:
            $ref: "#/components/schemas/ItemObject"
        discount:
          type: number
        storeId:
          type: string
        orderType:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        deliveryAddress:
          type: string

    payment_SubmitOrderResponse:
      description: This object is expected as output
      type: object
      properties:
        orderId:
          type: string
        message:
          type: string
          description: Will contain a descriptive error message if response code is not 200, else will be empty
        success:
          type: boolean
        timestamp:
          type: string

    payment_GetStatusRequest:
      description: This object is expected as input
      type: object
      properties:
        orderID:
          type: string

    payment_GetStatusResponse:
      description: This object is expected as output
      type: object
      properties:
        status:
          type: string
        success:
          type: boolean
        message:
          type: string
        timestamp:
          type: string

    payment_GetItemsRequest:
      description: This object is expected as input
      type: object
      properties:
        orderID:
          type: string

    payment_GetItemsResponse:
      description: This object is expected as output
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ItemObject"
        success:
          type: boolean
        message:
          type: string
        timestamp:
          type: string

    payment_GetCustomersActiveOrdersRequest:
      description: This object is expected as input
      type: object
      properties:
        jwtToken:
          type: string

    payment_GetCustomersActiveOrdersResponse:
      description: This object is expected as output
      type: object
      properties:
        orderID:
          type: string
        hasActiveOrder:
          type: boolean
        message:
          type: string

    GeoPointObject:
      description: This is a geoPoint object
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
        address:
          type: string

    payment_GetOrderRequest:
      description: This object is expected as input
      type: object
      properties:
        orderID:
          type: string

    payment_GetOrderResponse:
      description: This object is expected as output
      type: object
      properties:
        order:
          $ref: "#/components/schemas/OrderObject"
        success:
          type: boolean
        timestamp:
          type: string
        message:
          type: string

    payment_GetOrdersRequest:
      description: This object is expected as input
      type: object

    payment_GetOrdersResponse:
      description: This object is expected as output
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: "#/components/schemas/OrderObject"
        success:
          type: boolean
        timestamp:
          type: string
        message:
          type: string
