openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description: The library service

tags:
  - name: "Notification"

paths:

  /notification/sendEmailNotification:
    post:
      summary: Endpoint for sending an email notification
      tags:
        - "notification"
      description: Refer to summary
      operationId: sendEmailNotification
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/notification_SendEmailNotificationRequest"
      responses:
        "200":
          description: Returns whether the email was sent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notification_SendEmailNotificationResponse"


  /notification/sendDirectEmailNotification:
    post:
      summary: Endpoint for sending a direct email notification
      tags:
        - "notification"
      description: Refer to summary
      operationId: sendDirectEmailNotification
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/notification_SendDirectEmailNotificationRequest"
      responses:
        "200":
          description: Returns whether the email was sent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notification_SendDirectEmailNotificationResponse"

  /notification/sendPDFEmail:
    post:
      summary: Endpoint for sending a PDF email notification
      tags:
        - "notification"
      description: Refer to summary
      operationId: sendPDFEmail
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/notification_SendPDFEmailRequest"
      responses:
        "200":
          description: Returns whether the email was sent
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/notification_SendPDFEmailResponse"

components:

  schemas:


    notification_SendEmailNotificationRequest:
      description: This object is expected as input
      type: object
      properties:
        message:
          type: string
          description: This is the message that will be sent as a notification
        properties:
          type: object
          additionalProperties:
            type: string
          description: Hash map that needs to contain the Type (e.g delivery), Subject, UserType (e.g admin) and the UserID

    notification_SendEmailNotificationResponse:
      description: This object is expected as output
      type: object
      properties:
        responseMessage:
          type: string
          description: Will contain a descriptive error message if response code is not 200, else will be empty
        success:
          type: boolean

    notification_SendDirectEmailNotificationRequest:
      description: This object is expected as input
      type: object
      properties:
        message:
          type: string
          description: This is the message that will be sent as a notification
        properties:
          type: object
          additionalProperties:
            type: string
          description: Hash map that needs to contain the Subject and the email

    notification_SendDirectEmailNotificationResponse:
      description: This object is expected as output
      type: object
      properties:
        responseMessage:
          type: string
          description: Will contain a descriptive error message if response code is not 200, else will be empty
        isSuccess:
          type: boolean

    notification_SendPDFEmailRequest:
      description: This object is expected as input
      type: object
      properties:
        email:
          type: string
        PDF:
          type: string
          format: byte

    notification_SendPDFEmailResponse:
      description: This object is expected as output
      type: object
      properties:
        responseMessage:
          type: string
        isSuccess:
          type: boolean