openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description: The library service

tags:
  - name: "Recommendation"

paths:
  /recommendation/getCartRecommendation:
    post:
      summary: Endpoint for getting recommendation for a cart
      tags:
        - "recommendation"
      description: Refer to summary
      operationId: getCartRecommendation
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/recommendation_getCartRecommendationRequest"
      responses:
        "200":
          description: Returns the recommended items
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/recommendation_getCartRecommendationResponse"

  /recommendation/generateRecommendationTable:
    post:
      summary: Endpoint for creating recommendation table
      tags:
        - "recommendation"
      description: Refer to summary
      operationId: generateRecommendationTable
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/recommendation_generateRecommendationTableRequest"
      responses:
        "200":
          description: Returns the recommender table
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/recommendation_generateRecommendationTableResponse"

  /recommendation/generateRecommendationTablePDF:
    post:
      summary: Endpoint for creating recommendation table PDF
      tags:
        - "recommendation"
      description: Refer to summary
      operationId: generateRecommendationTablePDF
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/recommendation_generateRecommendationTablePDFRequest"
      responses:
        "200":
          description: Returns the recommender table
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/recommendation_generateRecommendationTablePDFResponse"

components:

  schemas:

    ItemObject:
      description: "Generic schema for an item"
      type: object
      properties:
        productID:
          type: string
        name:
          type: string
        barcode:
          type: string
        storeID:
          type: string
        price:
          type: number
        quantity:
          type: integer
        description:
          type: string
        imageUrl:
          type: string
        brand:
          type: string
        size:
          type: string
        itemType:
          type: string
        soldOut:
          type: boolean

    recommendation_getCartRecommendationRequest:
      description: This object is expected as input
      type: object
      properties:
        itemIDs:
          type: array
          items:
            type: string
        storeOneID:
          type: string
        storeTwoID:
          type: string
        storeThreeID:
          type: string

    recommendation_getCartRecommendationResponse:
      description: This object is returned as output
      type: object
      properties:
        recommendations:
          type: array
          items:
            $ref: "#/components/schemas/CartItemObject"
        isSuccess:
          type: boolean
        message:
          type: string

    CartItemObject:
      description: "Generic schema for a cart item"
      type: object
      properties:
        productID:
          type: string
        name:
          type: string
        barcode:
          type: string
        storeID:
          type: string
        price:
          type: number
        quantity:
          type: integer
        description:
          type: string
        imageUrl:
          type: string
        brand:
          type: string
        size:
          type: string
        itemType:
          type: string
        orderID:
          type: string
        totalCost:
          type: number
        cartItemNo:
          type: string

    recommendation_generateRecommendationTableRequest:
      description: This object is expected as input
      type: object

    recommendation_generateRecommendationTableResponse:
      description: This object is returned as output
      type: object
      properties:
        recommendationTable:
          type: array
          items:
            type: array
            items:
              type: string
        isSuccess:
          type: boolean
        message:
          type: string

    recommendation_generateRecommendationTablePDFRequest:
      description: This object is expected as input
      type: object
      properties:
        email:
          type: string

    recommendation_generateRecommendationTablePDFResponse:
      description: This object is returned as output
      type: object
      properties:
        isSuccess:
          type: boolean
        message:
          type: string