name: flutter_employee_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  email_validator: '^1.0.6'
  password_validator: '^0.0.1'
  flutter_secure_storage: ^4.2.1
  get_it: ^7.1.3
  loading_overlay: ^0.2.1
  font_awesome_flutter: ^9.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.0.0+2
  rxdart: ^0.20.0
  line_awesome_flutter: ^2.0.0
  animated_theme_switcher: "^2.0.1"
  provider: ^5.0.0
  barcode_widget: ^2.0.1
  flutter_barcode_scanner:
  sliding_up_panel: ^2.0.0+1
  drag_and_drop_gridview: ^1.0.8
  google_maps_flutter: "2.0.6"
  permission_handler: ^8.1.4+2
  location:
  flutter_polyline_points: ^1.0.0
  curved_navigation_bar:
  rflutter_alert: ^2.0.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


dev_dependencies:
  flutter_test:
    sdk: flutter
  http:
  build_runner:
  mockito: ^5.0.14


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/driver.jpg
    - assets/shopper.png
    - assets/admin.png
    - assets/profile.jpg
    - assets/delivery_truck.png
    - assets/shop/boxer.png
    - assets/shop/checkers.png
    - assets/shop/foodLoversMarket.png
    - assets/shop/game.png
    - assets/shop/pep.png
    - assets/shop/pnp.png
    - assets/shop/shop_checkers.png
    - assets/shop/superSpar.png
    - assets/shop/woolworths.png
    - assets/item/barOne.png
    - assets/item/blueRibbon.png
    - assets/item/creamyButternut.png
    - assets/item/creamyTomato.png
    - assets/item/custard.png
    - assets/item/jammers.png
    - assets/item/kellogNoodles.png
    - assets/item/kooBeans.png
    - assets/item/nescaffeCoffee.png
    - assets/item/oreo.png
    - assets/item/originalOros.png
    - assets/item/pnp_milk.png
    - assets/item/pnpMilk.png
    - assets/item/ricoffy.png
    - assets/item/sasko_bread.png
    - assets/item/strawberryYoghurt.png
    - assets/item/thickSlice.png
    - assets/item/tomato.png
    - assets/item/tomatoSauce.png
    - assets/item/weetBix.png
    - assets/item/woolworthsAppleJuice.png
    - assets/item/woolworthsCheese.png
    - assets/item/woolworthsMilk.png
    - assets/grocery.jpg
    - assets/cart.png
    - assets/driver.png
    - assets/pin.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
