openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description: The library service

tags:
  - name: "Importer"

paths:

  /importer/itemsCSVImporter:
    post:
      summary: Endpoint for creating monthly report
      tags:
        - "Importer"
      description: Refer to summary
      operationId: itemsCSVImporter
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/importer_ItemsCSVImporterRequest"
      responses:
        "200":
          description: Returns response message upon successful importing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/importer_ItemsCSVImporterResponse"

  /importer/storesCSVImporter:
    post:
      summary: Endpoint for creating monthly report
      tags:
        - "Importer"
      description: Refer to summary
      operationId: storesCSVImporter
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/importer_StoresCSVImporterRequest"
      responses:
        "200":
          description: Returns response message upon successful importing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/importer_StoresCSVImporterResponse"

components:

  schemas:

    importer_ItemsCSVImporterRequest:
      description: This object is expected as input
      type: object
      properties:
        file:
          type: string

    importer_ItemsCSVImporterResponse:
      description: This object is expected as output
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        timestamp:
          type: string

    importer_StoresCSVImporterRequest:
      description: This object is expected as input
      type: object
      properties:
        file:
          type: string

    importer_StoresCSVImporterResponse:
      description: This object is expected as output
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        timestamp:
          type: string