openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description: The library service

tags:
  - name: "Importer"

paths:

  /importer/itemsCSVImporter:
    post:
      summary: Endpoint for creating monthly report
      tags:
        - "Importer"
      description: Refer to summary
      operationId: itemsCSVImporter
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/importer_ItemsCSVImporterRequest"
      responses:
        "200":
          description: Returns response message upon successful importing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/importer_ItemsCSVImporterResponse"

  /importer/storesCSVImporter:
    post:
      summary: Endpoint for creating monthly report
      tags:
        - "Importer"
      description: Refer to summary
      operationId: storesCSVImporter
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/importer_StoresCSVImporterRequest"
      responses:
        "200":
          description: Returns response message upon successful importing
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/importer_StoresCSVImporterResponse"

components:

  schemas:

    ItemObject:
      description: "Generic schema for an item"
      type: object
      properties:
        productId:
          type: string
        name:
          type: string
        barcode:
          type: string
        storeId:
          type: string
        price:
          type: number
        quantity:
          type: integer
        description:
          type: string
        imageUrl:
          type: string
        brand:
          type: string
        size:
          type: string
        itemType:
          type: string

    ShopperObject:
      description: "Generic schema for a shopper"
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        password:
          type: string
        activationDate:
          type: string
        activationCode:
          type: string
        resetCode:
          type: string
        resetExpiration:
          type: string
        accountType:
          type: string
        shopperID:
          type: string
        storeID:
          type: string
        ordersCompleted:
          type: integer
        onShift:
          type: boolean
        isActive:
          type: boolean

    StoreObject:
      description: "Generic schema for a store"
      type: object
      properties:
        storeID:
          type: string
        storeBrand:
          type: string
        isOpen:
          type: boolean
        maxShoppers:
          type: integer
        maxOrders:
          type: integer
        openingTime:
          type: integer
        closingTime:
          type: integer
        imageUrl:
          type: string
        storeLocation:
          $ref: "#/components/schemas/GeoPointObject"

    OrderObject:
      description: "Generic schema for an Order"
      type: object
      properties:
        orderId:
          type: string
        userId:
          type: string
        storeId:
          type: string
        shopperId:
          type: string
        createDate:
          type: string
        processDate:
          type: string
        totalPrice:
          type: number
        status:
          type: string
        items:
          type: array
          items:
            $ref: "#/components/schemas/ItemObject"
        discount:
          type: number
        deliveryAddress:
          type: string
        storeAddress:
          type: string
        requiresPharmacy:
          type: boolean

    GroceryListObject:
      description: "Generic schema for a GroceryList"
      type: object
      properties:
        groceryListID:
          type: string
        name:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/ItemObject'


    UserObject:
      description: "Generic schema for a User"
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        password:
          type: string
        activationDate:
          type: string
        activationCode:
          type: string
        resetCode:
          type: string
        resetExpiration:
          type: string
        accountType:
          type: string

    DriverObject:
      description: "Generic schema for a Driver"
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        password:
          type: string
        activationDate:
          type: string
        activationCode:
          type: string
        resetCode:
          type: string
        resetExpiration:
          type: string
        accountType:
          type: string
        driverID:
          type: string
        rating:
          type: number
        onShift:
          type: boolean
        currentAddress:
          $ref: "#/components/schemas/GeoPointObject"
        deliveriesCompleted:
          type: number
        deliveryID:
          type: string

    CustomerObject:
      description: "Generic schema for a Customer"
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        password:
          type: string
        activationDate:
          type: string
        activationCode:
          type: string
        resetCode:
          type: string
        resetExpiration:
          type: string
        accountType:
          type: string
        customerID:
          type: string
        address:
          type: string
        groceryLists:
          type: array
          items:
            $ref: '#/components/schemas/GroceryListObject'
        shoppingCart:
          type: array
          items:
            $ref: "#/components/schemas/ItemObject"
        preference:
          type: object
        wallet:
          type: object

    AdminObject:
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        password:
          type: string
        activationDate:
          type: string
        activationCode:
          type: string
        resetCode:
          type: string
        resetExpiration:
          type: string
        accountType:
          type: string
        adminID:
          type: string

    GeoPointObject:
      description: This is a geoPoint object
      type: object
      properties:
        latitude:
          type: number
        longitude:
          type: number
        address:
          type: string

    OrderItemsObject:
      description: "Generic schema for an order item"
      type: object
      properties:
        productId:
          type: string
        name:
          type: string
        barcode:
          type: string
        orderId:
          type: string
        price:
          type: number
        quantity:
          type: integer
        description:
          type: string
        imageUrl:
          type: string
        brand:
          type: string
        size:
          type: string
        itemType:
          type: string
        totalCost:
          type: number

    importer_ItemsCSVImporterRequest:
      description: This object is expected as input
      type: object
      properties:
        file:
          type: string

    importer_ItemsCSVImporterResponse:
      description: This object is expected as output
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        timestamp:
          type: string

    importer_StoresCSVImporterRequest:
      description: This object is expected as input
      type: object
      properties:
        file:
          type: string

    importer_StoresCSVImporterResponse:
      description: This object is expected as output
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        timestamp:
          type: string