openapi: 3.0.0

info:
  version: 0.0.1
  title: Library Service
  description: The library service

tags:
  - name: "Shopping"
  - name: "Payment"


paths:

  /shopping/getItems:
    post:
      summary: Endpoint for Get Items use case
      tags:
        - "Shopping"
      description: Refer to summary
      operationId: getItems
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/shopping_GetItemsRequest"
      responses:
        "200":
          description: Returns items upon success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/shopping_GetItemsResponse"


  /shopping/addShopper:
    post:
      summary: Endpoint for adding shopper to shopper list
      tags:
        - "Shopping"
      description: Refer to summary
      operationId: addShopper
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/shopping_AddShopperRequest"
      responses:
        "200":
          description: Returns upon success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/shopping_AddShopperResponse"


  /shopping/getShoppers:
    post:
      summary: Endpoint for Get Shoppers use case
      tags:
        - "Shopping"
      description: Refer to summary
      operationId: getShoppers
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/shopping_GetShoppersRequest"
      responses:
        "200":
          description: Returns upon success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/shopping_GetShoppersResponse"

  /shopping/removeQueuedOrder:
    post:
      summary: Endpoint for removing a queued order.
      tags:
        - "Shopping"
      description: Refer to summary
      operationId: removeQueuedOrder
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
               $ref: "#/components/schemas/shopping_RemoveQueuedOrderRequest"
      responses:
        "200":
          description: Returns upon success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/shopping_RemoveQueuedOrderResponse"

  /shopping/getStores:
    post:
      summary: Endpoint for Get Stores use case
      tags:
        - "Shopping"
      description: Refer to summary
      operationId: getStores
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/shopping_GetStoresRequest"
      responses:
        "200":
          description: Returns upon success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/shopping_GetStoresResponse"



  /payment/updateOrder:
    post:
      summary: Endpoint for the Update Order use case
      tags:
        - "Payment"
      description: Refer to summary
      operationId: updateOrder
      requestBody:
        description: The input body required by this request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/payment_UpdateOrderRequest"
      responses:
        "200":
          description: Returns updated order upon success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/payment_UpdateOrderResponse"

components:

  schemas:


    ItemObject:
      description: "Generic schema for an item"
      type: object
      properties:
        productId:
          type: string
        name:
          type: string
        barcode:
          type: string
        storeId:
          type: string
        price:
          type: number
        quantity:
          type: integer
        description:
          type: string
        imageUrl:
          type: string

    shopping_GetItemsRequest:
      description: This object is expected as input
      type: object
      properties:
        jwtToken:
          type: string
          description: generated token used to identify the caller of the endpoint
        storeID:
          type: string

    shopping_GetItemsResponse:
      description: This object is returned as output
      type: object
      properties:
        errorMessage:
          type: string
          description: Will contain a descriptive error message if response code is not 200, else will be empty
        items:
          type: array
          items:
            $ref: "#/components/schemas/itemObject"


    shopping_AddShopperRequest:
      description: This object is expected as input
      type: object
      properties:
        shopperID:
          type: string
        storeID:
          type: string

    shopping_AddShopperResponse:
      description: This object is output
      type: object
      properties:
        success:
          type: boolean
          description: generated token used to identify the caller of the endpoint
        date:
          type: string
        message:
          type: string

    shopping_RemoveQueuedOrderRequest:
      description: this object is expected as input
      type: object
      properties:
        orderID:
          type: string
        storeID:
          type: string

    shopping_RemoveQueuedOrderResponse:
      description: this object is output
      type: object
      properties:
        isRemoved:
          type: boolean
        message:
          type: string
        orderID:
          type: string

    ShopperObject:
      description: "Generic schema for a shopper"
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        password:
          type: string
        storeID:
          type: string
        name:
          type: string
        surname:
          type: string
        ordersCompleted:
          type: integer

    shopping_GetShoppersRequest:
      description: This object is expected as input
      type: object
      properties:
        jwtToken:
          type: string
          description: generated token used to identify the caller of the endpoint
        storeID:
          type: string

    shopping_GetShoppersResponse:
      description: This object is expected as input
      type: object
      properties:
        errorMessage:
          type: string
          description: Will contain a descriptive error message if response code is not 200, else will be empty
        shoppers:
          type: array
          items:
            $ref: "#/components/schemas/ShopperObject"

    StoreObject:
      description: "Generic schema for a store"
      type: object
      properties:
        storeID:
          type: string
        storeBrand:
          type: string
        isOpen:
          type: boolean
        maxShoppers:
          type: integer
        maxOrders:
          type: integer
        openingTime:
          type: integer
        closingTime:
          type: integer
        orderQueue:
          type: array
        currentOrders:
          type: array
        shoppers:
          type: array
        stock:
          type: object

    shopping_GetStoresRequest:
      description: This object is expected as input
      type: object
      properties:

    shopping_GetStoresResponse:
      description: This object is expected as input
      type: object
      properties:
        response:
          type: boolean
        message:
            type: string
        stores:
          type: array
          items:
            $ref: "#/components/schemas/StoreObject"


    OrderObject:
      description: "Generic schema for an Order"
      type: object
      properties:
        orderId:
          type: string
        userId:
          type: string
        storeId:
          type: string
        shopperId:
          type: string
        createDate:
          type: string
        processDate:
          type: string
        totalPrice:
          type: number
        status:
          type: string
        items:
          type: array
        discount:
          type: number
        deliveryAddress:
          type: string
        storeAddress:
          type: string
        requiresPharmacy:
          type: boolean

    payment_UpdateOrderRequest:
      description: This object is expected as input
      type: object
      properties:
        orderId:
          type: string
          description: the id of the order to be generated
        userId:
          type: string
          description: generated token used to identify the caller of the endpoint
        items:
          type: array
          items:
            $ref: "#/components/schemas/itemObject"
        discount:
          type: number
        orderType:
          type: string
        deliveryAddress:
          type: string

    payment_UpdateOrderResponse:
      description: This object is expected as output
      type: object
      properties:
        message:
          type: string
          description: Will contain a descriptive error message if response code is not 200, else will be empty
        success:
          type: boolean
        timestamp:
          type: string
        order:
          type: object
